import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1751333339349 implements MigrationInterface {
    name = 'Init1751333339349'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "subcategories" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(100) NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT (1), "priority" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "categoryId" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(100) NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT (1), "priority" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "content_history" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "action" varchar CHECK( "action" IN ('created','updated','status_changed','deleted') ) NOT NULL, "previousData" text, "newData" text, "changes" text, "notes" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "contentId" integer NOT NULL, "userId" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "contents" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar(200) NOT NULL, "description" text NOT NULL, "tags" text NOT NULL, "status" varchar CHECK( "status" IN ('draft','published','archived') ) NOT NULL DEFAULT ('draft'), "priority" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "authorId" integer NOT NULL, "lastUpdatedById" integer, "categoryId" integer, "subcategoryId" integer)`);
        await queryRunner.query(`CREATE TABLE "project_statuses" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(100) NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT (1), "priority" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_132b83f5890525f549bce107949" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "project_areas" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(100) NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT (1), "priority" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_046ecb768e436836e0077f3137f" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "project_history" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "action" varchar CHECK( "action" IN ('created','updated','status_changed','area_changed','conclusion_added','deleted') ) NOT NULL, "changes" text, "notes" text, "previousData" text, "newData" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "projectId" integer NOT NULL, "userId" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar(200) NOT NULL, "description" text NOT NULL, "target" text NOT NULL, "conclusion" text, "priority" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "authorId" integer NOT NULL, "lastUpdatedById" integer, "statusId" integer NOT NULL, "areaId" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "users" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(100) NOT NULL, "email" varchar NOT NULL, "password" varchar NOT NULL, "role" varchar CHECK( "role" IN ('admin','creator') ) NOT NULL DEFAULT ('creator'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE TABLE "temporary_subcategories" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(100) NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT (1), "priority" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "categoryId" integer NOT NULL, CONSTRAINT "FK_d1fe096726c3c5b8a500950e448" FOREIGN KEY ("categoryId") REFERENCES "categories" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_subcategories"("id", "name", "description", "isActive", "priority", "createdAt", "updatedAt", "categoryId") SELECT "id", "name", "description", "isActive", "priority", "createdAt", "updatedAt", "categoryId" FROM "subcategories"`);
        await queryRunner.query(`DROP TABLE "subcategories"`);
        await queryRunner.query(`ALTER TABLE "temporary_subcategories" RENAME TO "subcategories"`);
        await queryRunner.query(`CREATE TABLE "temporary_content_history" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "action" varchar CHECK( "action" IN ('created','updated','status_changed','deleted') ) NOT NULL, "previousData" text, "newData" text, "changes" text, "notes" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "contentId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "FK_1739c37e5f698df4cb430c72c05" FOREIGN KEY ("contentId") REFERENCES "contents" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_b05a1646ac1d7dd1c0fa0112621" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_content_history"("id", "action", "previousData", "newData", "changes", "notes", "createdAt", "contentId", "userId") SELECT "id", "action", "previousData", "newData", "changes", "notes", "createdAt", "contentId", "userId" FROM "content_history"`);
        await queryRunner.query(`DROP TABLE "content_history"`);
        await queryRunner.query(`ALTER TABLE "temporary_content_history" RENAME TO "content_history"`);
        await queryRunner.query(`CREATE TABLE "temporary_contents" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar(200) NOT NULL, "description" text NOT NULL, "tags" text NOT NULL, "status" varchar CHECK( "status" IN ('draft','published','archived') ) NOT NULL DEFAULT ('draft'), "priority" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "authorId" integer NOT NULL, "lastUpdatedById" integer, "categoryId" integer, "subcategoryId" integer, CONSTRAINT "FK_21fa2829c68333e180618ecaae5" FOREIGN KEY ("authorId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_3616b627b6f8a285469ae7b4ffe" FOREIGN KEY ("lastUpdatedById") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_c59e928ccd0290a644b90d5bf60" FOREIGN KEY ("categoryId") REFERENCES "categories" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_7f78909e257dd46b3869fd5c0b5" FOREIGN KEY ("subcategoryId") REFERENCES "subcategories" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_contents"("id", "title", "description", "tags", "status", "priority", "createdAt", "updatedAt", "authorId", "lastUpdatedById", "categoryId", "subcategoryId") SELECT "id", "title", "description", "tags", "status", "priority", "createdAt", "updatedAt", "authorId", "lastUpdatedById", "categoryId", "subcategoryId" FROM "contents"`);
        await queryRunner.query(`DROP TABLE "contents"`);
        await queryRunner.query(`ALTER TABLE "temporary_contents" RENAME TO "contents"`);
        await queryRunner.query(`CREATE TABLE "temporary_project_history" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "action" varchar CHECK( "action" IN ('created','updated','status_changed','area_changed','conclusion_added','deleted') ) NOT NULL, "changes" text, "notes" text, "previousData" text, "newData" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "projectId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "FK_529523d050a87fdb2009de86527" FOREIGN KEY ("projectId") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_307d8c0f9e821eaa24af641c9cb" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_project_history"("id", "action", "changes", "notes", "previousData", "newData", "createdAt", "projectId", "userId") SELECT "id", "action", "changes", "notes", "previousData", "newData", "createdAt", "projectId", "userId" FROM "project_history"`);
        await queryRunner.query(`DROP TABLE "project_history"`);
        await queryRunner.query(`ALTER TABLE "temporary_project_history" RENAME TO "project_history"`);
        await queryRunner.query(`CREATE TABLE "temporary_projects" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar(200) NOT NULL, "description" text NOT NULL, "target" text NOT NULL, "conclusion" text, "priority" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "authorId" integer NOT NULL, "lastUpdatedById" integer, "statusId" integer NOT NULL, "areaId" integer NOT NULL, CONSTRAINT "FK_284d88f48163afb6eea98c8b0fc" FOREIGN KEY ("authorId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_c7772462e7f51f70c6233f9c23c" FOREIGN KEY ("lastUpdatedById") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_5a833dfa646b99b852c67dd8593" FOREIGN KEY ("statusId") REFERENCES "project_statuses" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION, CONSTRAINT "FK_15839a94f063652c97311acd0d8" FOREIGN KEY ("areaId") REFERENCES "project_areas" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_projects"("id", "title", "description", "target", "conclusion", "priority", "createdAt", "updatedAt", "authorId", "lastUpdatedById", "statusId", "areaId") SELECT "id", "title", "description", "target", "conclusion", "priority", "createdAt", "updatedAt", "authorId", "lastUpdatedById", "statusId", "areaId" FROM "projects"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`ALTER TABLE "temporary_projects" RENAME TO "projects"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "projects" RENAME TO "temporary_projects"`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar(200) NOT NULL, "description" text NOT NULL, "target" text NOT NULL, "conclusion" text, "priority" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "authorId" integer NOT NULL, "lastUpdatedById" integer, "statusId" integer NOT NULL, "areaId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "projects"("id", "title", "description", "target", "conclusion", "priority", "createdAt", "updatedAt", "authorId", "lastUpdatedById", "statusId", "areaId") SELECT "id", "title", "description", "target", "conclusion", "priority", "createdAt", "updatedAt", "authorId", "lastUpdatedById", "statusId", "areaId" FROM "temporary_projects"`);
        await queryRunner.query(`DROP TABLE "temporary_projects"`);
        await queryRunner.query(`ALTER TABLE "project_history" RENAME TO "temporary_project_history"`);
        await queryRunner.query(`CREATE TABLE "project_history" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "action" varchar CHECK( "action" IN ('created','updated','status_changed','area_changed','conclusion_added','deleted') ) NOT NULL, "changes" text, "notes" text, "previousData" text, "newData" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "projectId" integer NOT NULL, "userId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "project_history"("id", "action", "changes", "notes", "previousData", "newData", "createdAt", "projectId", "userId") SELECT "id", "action", "changes", "notes", "previousData", "newData", "createdAt", "projectId", "userId" FROM "temporary_project_history"`);
        await queryRunner.query(`DROP TABLE "temporary_project_history"`);
        await queryRunner.query(`ALTER TABLE "contents" RENAME TO "temporary_contents"`);
        await queryRunner.query(`CREATE TABLE "contents" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar(200) NOT NULL, "description" text NOT NULL, "tags" text NOT NULL, "status" varchar CHECK( "status" IN ('draft','published','archived') ) NOT NULL DEFAULT ('draft'), "priority" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "authorId" integer NOT NULL, "lastUpdatedById" integer, "categoryId" integer, "subcategoryId" integer)`);
        await queryRunner.query(`INSERT INTO "contents"("id", "title", "description", "tags", "status", "priority", "createdAt", "updatedAt", "authorId", "lastUpdatedById", "categoryId", "subcategoryId") SELECT "id", "title", "description", "tags", "status", "priority", "createdAt", "updatedAt", "authorId", "lastUpdatedById", "categoryId", "subcategoryId" FROM "temporary_contents"`);
        await queryRunner.query(`DROP TABLE "temporary_contents"`);
        await queryRunner.query(`ALTER TABLE "content_history" RENAME TO "temporary_content_history"`);
        await queryRunner.query(`CREATE TABLE "content_history" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "action" varchar CHECK( "action" IN ('created','updated','status_changed','deleted') ) NOT NULL, "previousData" text, "newData" text, "changes" text, "notes" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "contentId" integer NOT NULL, "userId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "content_history"("id", "action", "previousData", "newData", "changes", "notes", "createdAt", "contentId", "userId") SELECT "id", "action", "previousData", "newData", "changes", "notes", "createdAt", "contentId", "userId" FROM "temporary_content_history"`);
        await queryRunner.query(`DROP TABLE "temporary_content_history"`);
        await queryRunner.query(`ALTER TABLE "subcategories" RENAME TO "temporary_subcategories"`);
        await queryRunner.query(`CREATE TABLE "subcategories" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(100) NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT (1), "priority" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "categoryId" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "subcategories"("id", "name", "description", "isActive", "priority", "createdAt", "updatedAt", "categoryId") SELECT "id", "name", "description", "isActive", "priority", "createdAt", "updatedAt", "categoryId" FROM "temporary_subcategories"`);
        await queryRunner.query(`DROP TABLE "temporary_subcategories"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TABLE "project_history"`);
        await queryRunner.query(`DROP TABLE "project_areas"`);
        await queryRunner.query(`DROP TABLE "project_statuses"`);
        await queryRunner.query(`DROP TABLE "contents"`);
        await queryRunner.query(`DROP TABLE "content_history"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "subcategories"`);
    }

}
